//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// DECOS_alpha.rc에서 사용되고 있습니다.
//
#define IDD_DIALOG_CONN                 101
#define IDD_DIALOG_SERIAL               103
#define IDD_DIALOG_ADD                  107
#define IDD_DIALOG_HOSTPC               110
#define IDD_DIALOG_CD_IOT               112
#define IDD_DIALOG_INVERTER             114
#define IDD_DIALOG_ETC                  116
#define IDD_DIALOG_INSERTFILE           118
#define IDC_CURSOR_TEST                 120
#define IDI_ICON_TEST                   121
#define IDR_MENU_MAIN                   122
#define IDR_ACCELERATOR1                123
#define IDS_STRING_INTRO                124
#define IDD_DIALOG_DECMD                125
#define IDD_DIALOG_CRC                  127
#define IDB_BITMAP1                     129
#define IDC_STATIC_CONNTYPE             1001
#define IDC_RADIO_SERIAL                1002
#define IDC_STATIC_SETTING              1003
#define IDC_STATIC_PORT                 1004
#define IDC_STATIC_BR                   1005
#define IDC_STATIC_DBN                  1006
#define IDC_STATIC_PB                   1007
#define IDC_STATIC_SB                   1008
#define IDC_STATIC_FC                   1009
#define IDC_COMBO_PORT                  1010
#define IDC_COMBO_BR                    1011
#define IDC_COMBO_DBN                   1012
#define IDC_COMBO_PB                    1013
#define IDC_COMBO_SB                    1014
#define IDC_COMBO_FC                    1015
#define IDC_RADIO_DEFAULT               1016
#define IDC_STATIC_DN                   1017
#define IDC_STATIC_DT                   1018
#define IDC_EDIT_DN                     1019
#define IDC_COMBO_DT                    1020
#define IDC_CHECK_SIMUL                 1021
#define IDC_STATIC_DESCLIBE             1024
#define IDC_STATIC_DESCRIBE             1025
#define IDC_BUTTON_READALL              1026
#define IDC_BUTTON_WRITEALL             1027
#define IDC_BUTTON_DEFAULT              1028
#define IDC_EDIT_COUNTRY_N              1029
#define IDC_EDIT_AREA_N                 1030
#define IDC_EDIT_TE_N                   1031
#define IDC_EDIT_PHONE_N                1032
#define IDC_EDIT_INVERTER_C             1033
#define IDC_EDIT_COORDI_C               1034
#define IDC_EDIT_ARRAY_C                1035
#define IDC_EDIT_MSENSOR_C              1036
#define IDC_EDIT_DCPATH                 1037
#define IDC_STATIC_COUNTRY_N            1038
#define IDC_STATIC_AREA_N               1039
#define IDC_STATIC_TE_N                 1040
#define IDC_STATIC_PHONE_N              1041
#define IDC_STATIC_INVERTER_C           1042
#define IDC_BUTTON_EPSD_R               1043
#define IDC_STATIC_COORDI_C             1044
#define IDC_STATIC_ARRAY_C              1045
#define IDC_STATIC_MSENSOR_C            1046
#define IDC_STATIC_DCPATH               1047
#define IDC_BUTTON_EPSD_W               1048
#define IDC_STATIC_COORDI_G             1049
#define IDC_STATIC_MSENSOR_SG           1050
#define IDC_EDIT_COORDI_ID              1051
#define IDC_STATIC_COORDI_ID            1052
#define IDC_EDIT_COORDI_SN              1053
#define IDC_STATIC_COORDI_SN            1054
#define IDC_EDIT_MSENSOR_SID            1055
#define IDC_STATIC_MSENSOR_SID          1056
#define IDC_EDIT_MSENSOR_A_SID          1057
#define IDC_EDIT_MSENSOR_X_SPOS         1058
#define IDC_EDIT_MSENSOR_Y_SPOS         1059
#define IDC_EDIT_MSENSOR_SDCPATH        1060
#define IDC_STATIC_COORDI_ID2           1061
#define IDC_STATIC_MSENSOR_X_SPOS       1062
#define IDC_EDIT_MSENSOR_SSN            1063
#define IDC_EDIT_MSENSOR_SCID           1064
#define IDC_EDIT_MSENSOR_SINDEX         1065
#define IDC_BUTTON_COORDI_DR            1066
#define IDC_BUTTON_COORDI_DW            1067
#define IDC_BUTTON_ETC_READ             1068
#define IDC_BUTTON_ETC_WRITE            1069
#define IDC_STATIC_MSENSOR_Y_SPOS       1070
#define IDC_STATIC_MSENSOR_SDCPATH      1071
#define IDC_STATIC_MSENSOR_SSN          1072
#define IDC_STATIC_MSENSOR_SINDEX       1073
#define IDC_STATIC_MSENSOR_SCID         1074
#define IDC_STATIC_COORDI_EEPROM        1075
#define IDC_STATIC_INVERTER_G           1076
#define IDC_STATIC_INV0                 1077
#define IDC_CHECK_INV0                  1078
#define IDC_BUTTON_ETCCMD_CH0S          1079
#define IDC_STATIC_INV_ENABLE           1080
#define IDC_STATIC_INV_TYPE             1081
#define IDC_STATIC_INV_PHASE            1082
#define IDC_STATIC_INV_POWER            1083
#define IDC_STATIC_INV_TYPE2            1084
#define IDC_STATIC_INV_PROPERTY         1085
#define IDC_STATIC_G_CDMD               1086
#define IDC_BUTTON_INV_READ             1087
#define IDC_BUTTON_INV_WRITE            1088
#define IDC_STATIC_G_ZBMD               1089
#define IDC_BUTTON_ETCCMD_CH0R          1090
#define IDC_STATIC_G_INMD               1091
#define IDC_RADIO_INMD00                1092
#define IDC_RADIO_INMD01                1093
#define IDC_RADIO_INMD11                1094
#define IDC_RADIO_INMD21                1095
#define IDC_BUTTON_CDMD_READ            1096
#define IDC_BUTTON_ETCCMD_CH1S          1097
#define IDC_BUTTON_ETCCMD_CH1R          1098
#define IDC_BUTTON_ETCCMD_TXPK          1099
#define IDC_BUTTON_ETCCMD_IDSC          1100
#define IDC_BUTTON_ETCCMD_TIME          1101
#define IDC_STATIC_COORDI_EEPROM2       1102
#define IDC_BUTTON_CDMD_WRITE           1103
#define IDC_STATIC_G_PVEM               1104
#define IDC_STATIC_MSENSOR_AG           1105
#define IDC_EDIT_MSENSOR_SRN            1106
#define IDC_STATIC_COORDI_SSN           1107
#define IDC_BUTTON_READALL2             1108
#define IDC_STATIC_G_ETC                1109
#define IDC_STATIC_G_ETCCMD             1110
#define IDC_BUTTON_WRITEALL2            1111
#define IDC_BUTTON_MSENSOR_SREAD        1112
#define IDC_BUTTON_MSENSOR_SWRITE       1113
#define IDC_STATIC_G_LOMM               1114
#define IDC_RADIO_LOMM00                1115
#define IDC_RADIO_LOMM01                1116
#define IDC_RADIO_LOMM02                1117
#define IDC_STATIC_MSENSOR_V            1118
#define IDC_EDIT_MSENSOR_V              1119
#define IDC_STATIC_FIRMWARE_V           1120
#define IDC_STATIC_INV1                 1121
#define IDC_CHECK_INV1                  1122
#define IDC_EDIT_MSENSOR_CNT            1123
#define IDC_STATIC_MSENSOR_CNT          1124
#define IDC_RADIO_LOMM03                1125
#define IDC_STATIC_INV2                 1126
#define IDC_CHECK_INV2                  1127
#define IDC_STATIC_MSENSOR_STARTN       1128
#define IDC_BUTTON_STOP1                1128
#define IDC_BUTTON_STOP2                1129
#define IDC_BUTTON_MSENSOR_READADC      1130
#define IDC_STATIC_INV3                 1131
#define IDC_CHECK_INV3                  1132
#define IDC_STATIC_INV4                 1136
#define IDC_CHECK_INV4                  1137
#define IDC_STATIC_INV5                 1141
#define IDC_CHECK_INV5                  1142
#define IDC_STATIC_INV6                 1146
#define IDC_CHECK_INV6                  1147
#define IDC_EDIT_FIRMWARE_V             1151
#define IDC_EDIT_CH0R                   1152
#define IDC_EDIT_CH1R                   1153
#define IDC_EDIT_CH0S                   1154
#define IDC_EDIT_CH1S                   1155
#define IDC_EDIT_TIME                   1156
#define IDC_STATIC_EPSD_STATUS          1157
#define IDC_STATIC_INVERTER_STATUS      1158
#define IDC_STATIC_CDMD_STATUS          1159
#define IDC_STATIC_ETC_STATUS           1160
#define IDC_STATIC_INV7                 1161
#define IDC_CHECK_INV7                  1162
#define IDC_STATIC_ETCCMD_STATUS        1163
#define IDC_STATIC_MSENSOR_SSTATUS      1164
#define IDC_LIST_TEXTFILE               1165
#define IDC_STATIC_INV8                 1166
#define IDC_CHECK_INV8                  1167
#define IDC_BUTTON_INSERTFILE           1168
#define IDC_LIST_TEXTFILENAME           1169
#define IDC_STATIC_INSERTFILE           1170
#define IDC_STATIC_INV9                 1171
#define IDC_CHECK_INV9                  1172
#define IDC_RADIO_MSCH1                 1173
#define IDC_RADIO_MSCH2                 1174
#define IDC_STATIC_STATIC               1174
#define IDC_RADIO_MSCH4                 1175
#define IDC_EDIT_PCMDINSERT             1175
#define IDC_STATIC_INVA                 1176
#define IDC_STATIC_STATIC2              1176
#define IDC_RADIO_CRC8                  1176
#define IDC_CHECK_INVA                  1177
#define IDC_STATIC_STATIC3              1177
#define IDC_RADIO_CRC16                 1177
#define IDC_STATIC_STATIC4              1178
#define IDC_RADIO_CRC32                 1178
#define IDC_STATIC_STATIC5              1179
#define IDC_COMBO_CRCTYPE               1179
#define IDC_STATIC_STATIC6              1180
#define IDC_EDIT_PACKET                 1180
#define IDC_STATIC_INVB                 1181
#define IDC_STATIC_STATIC7              1181
#define IDC_EDIT_CRC                    1181
#define IDC_STATIC_NOTE1                1181
#define IDC_CHECK_INVB                  1182
#define IDC_STATIC_STATIC8              1182
#define IDC_STATIC_NOTE2                1182
#define IDC_CHECK_ABBI                  1183
#define IDC_STATIC_PAPIID               1184
#define IDC_CHECK_DASS                  1184
#define IDC_STATIC_PSTATUS              1185
#define IDC_CHECK_E_P3                  1185
#define IDC_STATIC_INVC                 1186
#define IDC_STATIC_POPTIONH             1186
#define IDC_CHECK_E_P5                  1186
#define IDC_CHECK_INVC                  1187
#define IDC_STATIC_PCKSUM               1187
#define IDC_CHECK_EKOS                  1187
#define IDC_STATIC_PCMD                 1188
#define IDC_CHECK_HANS                  1188
#define IDC_STATIC_PFRAMEID             1189
#define IDC_CHECK_HEXP                  1189
#define IDC_STATIC_POPTIONL             1190
#define IDC_CHECK_REFU                  1190
#define IDC_STATIC_INVD                 1191
#define IDC_CHECK_SUNG                  1191
#define IDC_CHECK_INVD                  1192
#define IDC_STATIC_STATIC10             1192
#define IDC_CHECK_WILL                  1192
#define IDC_STATIC_PDATA                1193
#define IDC_CHECK_REMSPV1P              1193
#define IDC_CHECK_REMSPV3P              1194
#define IDC_CHECK_SP1                   1195
#define IDC_STATIC_INVE                 1196
#define IDC_CHECK_SP2                   1196
#define IDC_CHECK_INVE                  1197
#define IDC_CHECK_SP3                   1197
#define IDC_CHECK_SP4                   1198
#define IDC_CHECK_SP5                   1199
#define IDC_CHECK_SP6                   1200
#define IDC_STATIC_INVF                 1201
#define IDC_CHECK_SP7                   1201
#define IDC_CHECK_INVF                  1202
#define IDC_CHECK_SP8                   1202
#define IDC_BUTTON_IDSCAN               1203
#define IDC_BUTTON_IDSTOP               1204
#define IDC_STATIC_GROUP1               1206
#define IDC_CHECK_DEBUG_MODE            1207
#define IDC_EDIT_INVCNT                 1207
#define IDC_STATIC_COORDI_STATUS        1208
#define IDC_CHECK_IDALL                 1208
#define IDC_STATIC_EEPROM_STATUS        1209
#define IDC_EDIT_RESULT_ID              1209
#define IDC_COMBO_INV0_TYPE             1210
#define IDC_COMBO_INVTYPE               1210
#define IDC_COMBO_INV1_TYPE             1211
#define IDC_STATIC_GROUP2               1211
#define IDC_COMBO_INV2_TYPE             1212
#define IDC_EDIT_INVID                  1212
#define IDC_EDIT_PCSPEC                 1212
#define IDC_COMBO_INV3_TYPE             1213
#define IDC_BUTTON_REQDATA              1213
#define IDC_EDIT_ETC_SPORTN             1213
#define IDC_COMBO_INV4_TYPE             1214
#define IDC_EDIT_RESULT_INVDATA         1214
#define IDC_EDIT_ETC_SRESULT            1214
#define IDC_COMBO_INV5_TYPE             1215
#define IDC_EDIT_ETC_SSEND              1215
#define IDC_COMBO_INV6_TYPE             1216
#define IDC_BUTTON_ETC_SSEND            1216
#define IDC_COMBO_INV7_TYPE             1217
#define IDC_EDIT_ETC_CPORTN             1217
#define IDC_COMBO_INV8_TYPE             1218
#define IDC_EDIT_ETC_CRESULT            1218
#define IDC_COMBO_INV9_TYPE             1219
#define IDC_EDIT_ETC_CSEND              1219
#define IDC_COMBO_INVA_TYPE             1220
#define IDC_BUTTON_ETC_CSEND            1220
#define IDC_COMBO_INVB_TYPE             1221
#define IDC_IPADDRESS_SERVER            1221
#define IDC_COMBO_INVC_TYPE             1222
#define IDC_BUTTON_ETC_SCONN            1222
#define IDC_COMBO_INVD_TYPE             1223
#define IDC_IPADDRESS_CLIENT            1223
#define IDC_COMBO_INVE_TYPE             1224
#define IDC_BUTTON_ETC_CCONN            1224
#define IDC_COMBO_INVf_TYPE             1225
#define IDC_BUTTON_ETC_CRECV            1225
#define IDC_EDIT_INV_ID0                1226
#define IDC_EDIT_INV_ID1                1227
#define IDC_EDIT_INV_ID2                1228
#define IDC_EDIT_INV_ID3                1229
#define IDC_EDIT_INV_ID4                1230
#define IDC_EDIT_INV_ID5                1231
#define IDC_EDIT_INV_ID6                1232
#define IDC_EDIT_INV_ID7                1233
#define IDC_EDIT_INV_ID8                1234
#define IDC_EDIT_INV_ID9                1235
#define IDC_EDIT_INV_ID10               1236
#define IDC_EDIT_INV_ID11               1237
#define IDC_EDIT_INV_ID12               1238
#define IDC_EDIT_INV_ID13               1239
#define IDC_EDIT_INV_ID14               1240
#define IDC_EDIT_INV_ID15               1241
#define IDC_EDIT_INV0_POWER             1242
#define IDC_EDIT_INV1_POWER             1243
#define IDC_EDIT_INV2_POWER             1244
#define IDC_EDIT_INV3_POWER             1245
#define IDC_EDIT_INV4_POWER             1246
#define IDC_EDIT_INV5_POWER             1247
#define IDC_EDIT_INV6_POWER             1248
#define IDC_EDIT_INV7_POWER             1249
#define IDC_EDIT_INV8_POWER             1250
#define IDC_EDIT_INV9_POWER             1251
#define IDC_EDIT_INVA_POWER             1252
#define IDC_EDIT_INVB_POWER             1253
#define IDC_EDIT_INVC_POWER             1254
#define IDC_EDIT_INVD_POWER             1255
#define IDC_EDIT_INVE_POWER             1256
#define IDC_EDIT_INVF_POWER             1257
#define IDC_RADIO_ZBMD00                1258
#define IDC_RADIO_ZBMD01                1259
#define IDC_RADIO_ZBMD02                1260
#define IDC_RADIO_ZBMD04                1261
#define IDC_RADIO_ZBMD11                1262
#define IDC_RADIO_ZBMD12                1263
#define IDC_RADIO_ZBMD14                1264
#define IDC_RADIO_ZBMD21                1265
#define IDC_RADIO_ZBMD22                1266
#define IDC_RADIO_ZBMD24                1267
#define IDC_RADIO_PVEM00                1268
#define IDC_RADIO_PVEM01                1269
#define IDC_RADIO_PVEM02                1270
#define IDC_RADIO_PVEM03                1271
#define IDC_RADIO_PVEM11                1272
#define IDC_RADIO_PVEM12                1273
#define IDC_RADIO_PVEM21                1274
#define IDC_RADIO_PVEM22                1275
#define IDC_COMBO_INV0_PHASE            1310
#define IDC_COMBO_INV1_PHASE            1311
#define IDC_COMBO_INV2_PHASE            1312
#define IDC_COMBO_INV3_PHASE            1313
#define IDC_COMBO_INV4_PHASE            1314
#define IDC_COMBO_INV5_PHASE            1315
#define IDC_COMBO_INV6_PHASE            1316
#define IDC_COMBO_INV7_PHASE            1317
#define IDC_COMBO_INV8_PHASE            1318
#define IDC_COMBO_INV9_PHASE            1319
#define IDC_COMBO_INVA_PHASE            1320
#define IDC_COMBO_INVB_PHASE            1321
#define IDC_COMBO_INVC_PHASE            1322
#define IDC_COMBO_INVD_PHASE            1323
#define IDC_COMBO_INVE_PHASE            1324
#define IDC_COMBO_INVF_PHASE            1325
#define ID_EDIT_HELP                    40001
#define ID_FILE_OPEN                    40002
#define ID_FILE_SAVE                    40003
#define ID_FILE_PRINT                   40004
#define ID_FILE_PRINT40005              40005
#define ID_FILE_EXIT                    40006
#define ID_HELP_VERSION                 40007
#define ID_HELP_                        40008
#define ID_FILE_SAVEAS                  40009
#define ID_HELP_HELP                    40010
#define ID_EDIT                         40013
#define ID_EDIT_SETPOS0                 40014
#define ID_VIEW_CHANGEBKCOLOR           40017
#define IDC_STATIC_EPSD_G               -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40020
#define _APS_NEXT_CONTROL_VALUE         1222
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
